<#
Can also be generated by running:
New-ModuleManifest
#>
@{
    RootModule		= 'TSAD'
    ModuleVersion	= '0.0.1'
    Author		= 'Toby Slight'
    Copyright		= '(c) Toby Slight. All rights reserved.'
    Description		= 'Extra abstraction layer for interacting with Active Directory.'
    RequiredModules	= @(
	'ActiveDirectory'
	'TSDate'
	'TSUtils'
    )
    FunctionsToExport	= '*'
    CmdletsToExport	= '*'
    VariablesToExport	= '*'
    AliasesToExport	= '*'
    PrivateData		= @{
	PSData		= @{
	}
    }
}
